language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t smusy/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true smusy/react-test npm test

after_success:
  - docker build -t smusy/multi-client ./client
  - docker build -t smusy/multi-nginx ./nginx
  - docker build -t smusy/multi-server ./server
  - docker build -t smusy/multi-worker ./worker
  # Log in the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-s
  # Take those images and push them to docker hub
  - docker push smusy/multi-client
  - docker push smusy/multi-nginx
  - docker push smusy/multi-server
  - docker push smusy/multi-worker